name: Fiore.vegas
favicon: null
layout_spectrum: 0.7700291168875992
typography_spectrum: 0.6338727117981762
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8363633134867996
  lightness: 0.7909141730051488
  saturation: 0.5099423073697835
  rhythmicContrast: 0.23485277546569705
purpose: []
