name: Fiore.vegas
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75434
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d83c7'
    - '#ffffff'
    - '#bfbfff'
    - '#00ffff'
    - '#0000ff'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.5099423073697835
  rhythmicContrast: 0.5
purpose: []
